### PR TITLE
Iteration4.md

### PR DESCRIPTION
**Pull request by Danie0918**
【Part 1】Along with the new UI version. [Released on 2023.10.11]

【PRD】

- [[Overview]](https://github.com/Magickbase/neuron-public-issues/pull/227#issuecomment-1639209340)
- [[Receive]](https://github.com/Magickbase/neuron-public-issues/pull/227#issuecomment-1639261056)
- [[Address Book]](https://github.com/Magickbase/neuron-public-issues/pull/227#issuecomment-1639286644)
- [[Set synchronization start block]](https://github.com/Magickbase/neuron-public-issues/pull/227#issuecomment-1639662537) 
- [[Rename the built-in CKB node]](https://github.com/Magickbase/neuron-public-issues/pull/227#issuecomment-1639666008) 

【UI】[https://github.com/Magickbase/visual-style-guide/issues/31](https://github.com/Magickbase/visual-style-guide/issues/31)

---

【Part 2】The Accompanying Light Client is about to be activated on the main network on or about November 1, and a new version will need to be released to support it.

【PRD】

1. [[Cell Management]](https://github.com/Magickbase/neuron-public-issues/pull/227#issuecomment-1639651746) 

2. [[Network settings optimization]](https://github.com/Magickbase/neuron-public-issues/pull/227#issuecomment-1774561197)    #200 #284 

【UI】

---

【Part 3】Other iteration requirements

1. [[Send]](https://github.com/Magickbase/neuron-public-issues/pull/227#issuecomment-1639583051) 
2. [[Optimization of hot/cold combinations for wallets] ](https://github.com/Magickbase/neuron-public-issues/pull/227#issuecomment-1774583849)   #288 
4. [[Same wallet import optimization]](https://github.com/Magickbase/neuron-public-issues/pull/227#issuecomment-1774607525)   #291 
5. [[Optimize the setting of sync start block in light client mode]](https://github.com/Magickbase/neuron-public-issues/pull/227#issuecomment-1774620449)   #304 
6. [[Optimize the receive page interaction]](https://github.com/Magickbase/neuron-public-issues/pull/227#issuecomment-1774624071)   #305 
7. [[Show estimation of synchronization metrics on Neuron's page]](https://github.com/Magickbase/neuron-public-issues/pull/227#issuecomment-1774675520)   #255  #235

【UI】https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=28438-26852&mode=design&t=AY5lLSGCmoHUwzpQ-0

### CODE REVIEW

**Comment by Danie0918** [comment]
【Overview】

-Requirement Description
1.Enhance the account concept by integrating sending and receiving into the account overview.
2.Allow user to manage cells.

-Requirement Contents
overview

1.Remove the separate levels of send and receive, and adjust the interaction between receive and send in the overview so that it is hierarchically below the overview.
2.Add Address Book and Cell Management portal located next to the balance.
3.Add locked balance display, click to view to go to the Cell Management page.

**Comment by Danie0918** [comment]
【Receive】

-Requirement Description：Since receive does not involve complex operations, using pop-ups will increase ease of use and reduce page jumps.

receive

-Requirement Contents
[General Wallet]
1.Receive will appear as a pop-up window and apply to the asset account.
2.Retain the original save and download QR code image function, retain the address copy and convert address format function.
3.Move the alert text next to the headline exclamation point and only float it when the user moves into focus.

[Hardware wallet]Replace the previous popup interaction with a button morphology change.
1.When a hardware wallet is used, a Verify Address button is provided.
2.Clicking the Verify button connects the wallet and provides a loading animation.
3.When the connection fails, a retry button is provided and an error message is prompted under the button.
4.Provides an authentication loading animation when the connection is successful, and displays an authentication button when authentication is complete.

**Comment by Danie0918** [comment]
【Address Book】

-Requirement Description:Due to the receive  adjustments, the address book as a separate function appears in the form of a pop-up window to show can effectively reduce the page jump to facilitate user operation.

address_book

-Requirement Contents
1.Add All/Receiving/Change type categories and show all by default.
2.Retain the original copy address/balance and edit description interactions.
3.Add balance and Txs sorting, click to switch to descending, ascending and restore default sorting status in turn.

**Comment by Danie0918** [comment]
【Send】

-Requirement Description:Support chained transactions, add transaction confirmation page.

send

-Requirement Contents
1.Send is categorized into chained and direct, and supports chained transactions.
2.Add transaction confirmation page.
-Transaction Hash:Displays the transaction hash and supports copying.
-Details:Displays the amount, number, size, cycles, and lock time of the transaction.（When not locked, the lock time is not displayed.）
-Topology Graph：Displays the inputs and outputs of the transaction. The full address is displayed in a floating layer when the mouse is moved over the address, and the address can be copied by clicking on it.
-Password：Enter password and verify it when the transaction is submitted.
-Submit Transaction：It is divided into chain in queue and direct send, displaying the loading animation and estimated time after submission, and displaying the result after the submission is completed.
3.After the transaction is submitted and leaves the send page, a pop-up window is required to alert the user if the chain transaction fails or is partially successful.

**Comment by Danie0918** [comment]
【Cell Management】

- Requirement Description:This page will display all live cells and allows users to manage them.

cell_management

- Requirement Contents
1. The Cell Management page displays the number and list of live cells and allows for the management of these cells.
- List Title：Display date, type, amount and status and support sorting.
[type:Identify the cell type based on the code script of the typep script.]
[Amount:The number of available CKB balances.]
- Description:Mouse over under the description of the entry can choose to click on Edit, input box to fill in the description of the content and click on the Enter or other areas after saving.Description text exceeds the length of the apostrophe instead of, mouse over the floating layer to display the full description.
- Operation:Support view details, lock/unlock and spend.
- Batch operation：The user can select the cells to be manipulated by clicking on the entry or select all cells for batch manipulation.
2. Details:Popup window showing cell's outpoint hash, lock script, type script, data and capacity.The outpoint hash supports copying and opening in a browser, and capacity displays the number of occupied and declared CKBs in a progress bar.
3. Support locking and unlocking cells, click the pop-up window to verify the password and confirm it to execute the operation and display the loading animation.
4. The spend cell will jump to the send page and bring in the full amount (including fees).

**Comment by Danie0918** [comment]
【Set synchronization start block 】

- Requirement Description:default node was used to denote the internal ckb node before. There're 2 problems:

1. Name convention of default node is not classical, typically it should be capitalized as Default Node
2. default node is not exactly what it represents, it was meant to be the built-in ckb node. But now, the default node can be modified freely.

rename_the_built-in_ckb_node

- Requirement Contents
1. The default node is renamed as Internal Node and cannot be modified or deleted like Light Client Testnet node.
2. Adjust the node ordering so that the default Internal Node and Light Client Testnet node are in the first two places.
3. New set default node function, the current default node will increase the label reminder, non-default nodes in the selected to provide set as the default node function, click set as the default node.

【Program for upgrading older versions】
1. Do not change the user's default node and name.
2. When a user has modified the built-in node, a new built-in node is added and the user-modified node is retained as a custom node.

**Comment by silySuper** [comment]
1.【Overview】contains entrances of cell management/transaction details /send  pageI/recevive page ,I am confused of which one has   sidebar tab entrance?
2.【Address Book】,in requirement Contents No.2  whether we need to consider when balance or Txs  are same ,when we click sort button ,how to sort?
2.【Send】,what is the difference between chain send、direct send and send 3 chained-TXs,what is the relationship between chain send and send 3 chained-TXs?

**Comment by Danie0918** [comment]
> 1.【Overview】contains entrances of cell management/transaction details /send pageI/recevive page ,I am confused of which one has sidebar tab entrance? 

The original send pageI/receive page, which had an entry in the sidebar, has been removed in this version.


>2.【Address Book】,in requirement Contents No.2 whether we need to consider when balance or Txs are same ,when we click sort button ,how to sort? 

With the same parameters, it is sorted according to the default sorting which is time descending.

>3.【Send】,what is the difference between chain send、direct send and send 3 chained-TXs,what is the relationship between chain send and send 3 chained-TXs?

Chain send and direct send are two different options for sending, chain send adds the transaction to the chain and direct send send sends it directly.And send 3 chained-TXs already existing chained transactions, providing a push-button action to help submit those transactions.

**Comment by Danie0918** [comment]
Adjustments have been made according to the content of the meeting:
1. [Overview] Add additional supplement "Add Send,Receive under Tool in the top menu bar."
2. [Address Book] add interactive description "Click All/Receiving/Change to restore the default sorting."
3. [Send] Adjusted the chain transaction flow and some texts.
4. [Cell Management] added some instructions and adjusted the process of consuming cells.
5. [Set synchronization start block] added additional entries and adjusted some texts.
6. [Rename the built-in CKB node] Removed the interaction related to setting the default node.

**Comment by Kirl70** [comment]
UI Design Draft: 

https://github.com/Magickbase/visual-style-guide/issues/31

**Comment by Danie0918** [comment]
【Network settings optimization 】Support for light client main network and optimization of known issues.

- Requirement Description:

1. [Bug] Currently there is no restriction on linking users to external nodes here, need to add restrictions like light client nodes.
2. [Feature] Support for light client main network.
3. [Feature] Supports main/test network switching for built-in node and light client node.

network_settings_optimization

- Requirement Contents
1. Internal node and light client node support manual switching between main and test network by clicking to switch to the corresponding network.
2. When the currently selected node is an internal node, a popup window is required to report an error when an external node is detected to be enabled.
- When no external network is added, a pop-up prompt directs the user to add a network to enable the external node.
- When external nodes have been added, a list of external nodes is displayed for the user to select, and the user can also choose to add new network nodes.
3. Pop-up window interactions：
- Pop-ups are only detected as alerts when the user opens the software or when switching to an internal network node.
- Click to cancel ignoring alerts and still link internal network nodes.
- Click Confirm only when selecting an external network node or the Add Network option.

**Comment by Danie0918** [comment]
【Optimization of hot/cold combinations for wallets】

- Requirement Description:The combination of hot/cold in the wallet is not smooth and the workflow needs to be optimized.

optimization_of_hot_cold_combinations_for_wallets

- Requirement Contents
1. Offline signing is not being supported to import signed transactions and to close the pop-up window when the signature is complete.
2. Added broadcast transaction:
- Unable to select when offline, support for watch-only account broadcasting.
- The broadcast shows the loading status and jumps to history when finished.
3. Pop-up window alert:
- Import signed transaction files in Offline Signature.
- Import unsigned transaction files in broadcast transaction.

**Comment by Danie0918** [comment]
【Same wallet import optimization】

- Requirement Description:Currently users can import the same wallet multiple times, which increases the complexity of management and needs to be optimized.

same_wallet_import_optimizationsame_wallet_import_optimization


- Requirement Contents
1. Importing duplicate wallets is no longer supported. When importing a duplicate wallet, the user is prompted to select an existing wallet to replace or cancel the import.
2. For users with the same wallet, a pop-up window prompts the user after updating the software and no longer pops up after the user closes or operates it.
- The pop-up window displays the same wallets grouped in the order of the existing wallets and provides a radio option for the user to select the wallets to be retained in each group.
- After selecting the wallets to keep, the user clicks Confirm to delete the unselected wallets in the same group.
- When no wallet is selected for the same grouping, no operations are performed on that group's wallets.
- The user may choose to operate and confirm only a portion of the grouped reserved wallets, but may not click to confirm without selecting any wallets.
3. Settings - Wallets Add option to detected duplicate wallets:
- This option is only available if the same wallet exists.
- Click to bring up the Detect Duplicate Wallet pop-up and proceed.

**Comment by Danie0918** [comment]
【Optimize the setting of sync start block in light client mode】

- Requirement Description:When the block number set by the user is after the historical transaction block number, then the historical transaction will not be synchronized, but displaying 100% synchronization can be misleading to the user.


optimize_the_setting_of_sync_start_block_in_light_client_mode


- Requirement Contents
1. Add a strong prompt when setting the starting block number and require 5 seconds before clicking to confirm the operation.
2. When the set block number is larger than the latest block it errors and changes the set block number to the latest block number, and it takes 5s to confirm.
3. Add manually set starting block in the Synchronization dropdown box to support opening the corresponding block in the Explorer.

**Comment by Danie0918** [comment]
【Optimize the receive page interaction】

- Requirement Description:There is no clear boundary between QR code and address string, so the button to copy QR code would be considered the button to copy address string.

optimize_the_receive_page_interaction


- Requirement Contents
1. Show actions when mouse over the QR code instead of adding a button next to it.
2. After clicking Copy, it shows that it has been copied.

**Comment by yanguoyu** [comment]
1. >【Network settings optimization 】 Internal node and light client node support manual switching between main and test network by clicking to switch to the corresponding network.

Should they choose network type when the users change the node data by settings? And, does this directory show the upper directory that includes mainnet and testnet data?
image


2. >【Network settings optimization 】 Pop-up window interactions：Click to cancel ignoring alerts and still link internal network nodes.

Currently, if the user starts an external node that uses port 8114, do we need to start with another port and change the display of the internal network URL? 


3. >【Network settings optimization 】 When no external network is added, a pop-up prompt directs the user to add a network to enable the external node.
When external nodes have been added, a list of external nodes is displayed for the user to select, and the user can also choose to add new network nodes.

Should we only show the network that its URL equals the started ckb node URL?

4. Does the light client node also use these interactions? currently, the light client node can use an internal node.

**Comment by yanguoyu** [comment]
1. > [Optimization of hot/cold combinations for wallets]  Added broadcast transaction:
support for watch-only account broadcasting.

I believe broadcast transactions can be for any wallet, but not a watch-only account.

**Comment by silySuper** [comment]
what is the meaning of this tip?
截屏2023-10-27 15 39 05

**Comment by Danie0918** [comment]
> what is the meaning of this tip? 截屏2023-10-27 15 39 05

This is to remind the user that setting the synchronization start block will affect the synchronization of historical data, so as to avoid the user from setting too high a block that will result in missing data for the user.

**Pull request merged**
